// src/react/number.editor.tsx
import * as React from "react";
import * as common from "../common";
import { TitleEditor } from "./title.editor";

export class NumberEditor extends React.Component<common.Props<common.NumberSchema, number>, {}> {
    public value?: number;
    public errorMessage: string;
    constructor(props: common.Props<common.ArraySchema, number>) {
        super(props);
        if (this.props.required) {
            this.value = common.getDefaultValue(this.props.schema, this.props.initialValue) as number;
        } else {
            this.value = undefined;
        }
        this.validate();
    }
    public componentDidMount() {
        if (this.value !== this.props.initialValue) {
            this.props.updateValue(this.value);
        }
    }
    public onChange = (e: React.FormEvent<{ value: string }>) => {
        this.value = this.props.schema.type === "integer" ? common.toInteger(e.target.value) : common.toNumber(e.target.value);
        this.validate();
        this.props.updateValue(this.value);
    }
    public validate() {
        if (this.value !== undefined) {
            if (this.props.schema.minimum !== undefined) {
                if (this.props.schema.exclusiveMinimum) {
                    if (this.value <= this.props.schema.minimum) {
                        this.errorMessage = this.props.locale.error.largerThan.replace("{0}", String(this.props.schema.minimum));
                        return;
                    }
                } else {
                    if (this.value < this.props.schema.minimum) {
                        this.errorMessage = this.props.locale.error.minimum.replace("{0}", String(this.props.schema.minimum));
                        return;
                    }
                }
            }
            if (this.props.schema.maximum !== undefined) {
                if (this.props.schema.exclusiveMaximum) {
                    if (this.value >= this.props.schema.maximum) {
                        this.errorMessage = this.props.locale.error.smallerThan.replace("{0}", String(this.props.schema.maximum));
                        return;
                    }
                } else {
                    if (this.value > this.props.schema.maximum) {
                        this.errorMessage = this.props.locale.error.maximum.replace("{0}", String(this.props.schema.maximum));
                        return;
                    }
                }
            }
        }

        this.errorMessage = "";
    }
    public toggleOptional = () => {
        if (this.value === undefined) {
            this.value = common.getDefaultValue(this.props.schema, this.props.initialValue) as number;
            this.validate();
        } else {
            this.value = undefined;
        }
        this.setState({ value: this.value });
        this.props.updateValue(this.value);
    }
    public render() {
        let control: JSX.Element | null = null;
        if (this.value !== undefined) {
            if (this.props.schema.enum === undefined || this.props.readonly || this.props.schema.readonly) {
                control = (
                    <input className={this.props.theme.formControl}
                        type="number"
                        onChange={this.onChange}
                        defaultValue={String(this.value)}
                        readOnly={this.props.readonly || this.props.schema.readonly} />
                );
            } else {
                const options = this.props.schema.enum.map((e, i) => <option key={i} value={e} >{e}</option>);
                control = (
                    <select className={this.props.theme.formControl}
                        type="number"
                        onChange={this.onChange}
                        defaultValue={String(this.value)} >
                        {options}
                    </select>
                );
            }
        }
        let errorDescription: JSX.Element | null = null;
        if (this.errorMessage) {
            errorDescription = <p className={this.props.theme.help}>{this.errorMessage}</p>;
        }
        let optionalCheckbox: JSX.Element | null = null;
        if (!this.props.required) {
            optionalCheckbox = (
                <div className={this.props.theme.optionalCheckbox}>
                    <label>
                        <input type="checkbox" onChange={this.toggleOptional} checked={this.value === undefined} />
                        is undefined
                    </label>
                </div>
            );
        }
        return (
            <div className={this.errorMessage ? this.props.theme.errorRow : this.props.theme.row}>
                <TitleEditor {...this.props} />
                {optionalCheckbox}
                {control}
                <p className={this.props.theme.help}>{this.props.schema.description}</p>
                {errorDescription}
            </div>
        );
    }
}

// src/angular/number-editor.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import * as common from "../common";

@Component({
    selector: "number-editor",
    template: `
    <div [class]="errorMessage ? theme.errorRow : theme.row">
        <title-editor [title]="title"
            (onDelete)="onDelete"
            [theme]="theme"
            [icon]="icon"
            [locale]="locale">
        </title-editor>
        <div *ngIf="!required" [class]="theme.optionalCheckbox">
            <label>
                <input type="checkbox" (change)="toggleOptional" [checked]="value === undefined" />
                is undefined
            </label>
        </div>
        <input *ngIf="useInput()"
            [class]="theme.formControl"
            type="number"
            (keyup)="onChange($event)"
            [defaultValue]="value"
            [readOnly]="readonly || schema.readonly" />
        <select *ngIf="useSelect()"
            [class]="theme.formControl"
            type="number"
            (change)="onChange">
            <option *ngFor="let e of schema.enum; let i = index; trackBy:trackByFunction"
                [value]="e"
                [selected]="value === e">
                {{e}}
            </option>
        </select>
        <p [class]="theme.help">{{schema.description}}</p>
        <p *ngIf="errorMessage" [class]="theme.help">{{errorMessage}}</p>
    </div>
    `,
})
export class NumberEditorComponent {
    @Input()
    schema: common.NumberSchema;
    @Input()
    initialValue: number;
    @Input()
    title?: string;
    @Output()
    updateValue = new EventEmitter();
    @Input()
    theme: common.Theme;
    @Input()
    icon: common.Icon;
    @Input()
    locale: common.Locale;
    @Output()
    onDelete?: () => void;
    @Input()
    readonly?: boolean;
    @Input()
    required?: boolean;

    value?: number;
    errorMessage: string;
    ngOnInit() {
        this.value = common.getDefaultValue(this.required, this.schema, this.initialValue) as number;
        // this.updateValue.emit(this.value);
    }
    useInput() {
        return this.value !== undefined && (this.schema.enum === undefined || this.readonly || this.schema.readonly);
    }
    useSelect() {
        return this.value !== undefined && (this.schema.enum !== undefined && !this.readonly && !this.schema.readonly);
    }
    onChange(e: { target: { value: string } }) {
        this.value = this.schema.type === "integer" ? common.toInteger(e.target.value) : common.toNumber(e.target.value);
        this.validate();
        this.updateValue.emit(this.value);
    }
    trackByFunction(index: number, value: number) {
        return index;
    }
    validate() {
        if (this.value !== undefined) {
            if (this.schema.minimum !== undefined) {
                if (this.schema.exclusiveMinimum) {
                    if (this.value <= this.schema.minimum) {
                        this.errorMessage = this.locale.error.largerThan.replace("{0}", String(this.schema.minimum));
                        return;
                    }
                } else {
                    if (this.value < this.schema.minimum) {
                        this.errorMessage = this.locale.error.minimum.replace("{0}", String(this.schema.minimum));
                        return;
                    }
                }
            }
            if (this.schema.maximum !== undefined) {
                if (this.schema.exclusiveMaximum) {
                    if (this.value >= this.schema.maximum) {
                        this.errorMessage = this.locale.error.smallerThan.replace("{0}", String(this.schema.maximum));
                        return;
                    }
                } else {
                    if (this.value > this.schema.maximum) {
                        this.errorMessage = this.locale.error.maximum.replace("{0}", String(this.schema.maximum));
                        return;
                    }
                }
            }
        }

        this.errorMessage = "";
    }
    toggleOptional() {
        if (this.value === undefined) {
            this.value = common.getDefaultValue(true, this.schema, this.initialValue) as number;
        } else {
            this.value = undefined;
        }
        // this.updateValue.emit(this.value);
    }
}
