// src/react/string.editor.tsx
import * as React from "react";
import * as common from "../common";
import { TitleEditor } from "./title.editor";

export class StringEditor extends React.Component<common.Props<common.StringSchema, string>, {}> {
    public value?: string;
    public errorMessage: string;
    constructor(props: common.Props<common.ArraySchema, string>) {
        super(props);
        if (this.props.required) {
            this.value = common.getDefaultValue(this.props.schema, this.props.initialValue) as string;
        } else {
            this.value = undefined;
        }
        this.validate();
    }
    public componentDidMount() {
        if (this.value !== this.props.initialValue) {
            this.props.updateValue(this.value);
        }
    }
    public onChange = (e: React.FormEvent<{ value: string }>) => {
        this.value = e.target.value;
        this.validate();
        this.props.updateValue(this.value);
    }
    public validate() {
        if (this.value !== undefined) {
            if (this.props.schema.minLength !== undefined
                && this.value.length < this.props.schema.minLength) {
                this.errorMessage = this.props.locale.error.minLength.replace("{0}", String(this.props.schema.minLength));
                return;
            }
            if (this.props.schema.maxLength !== undefined
                && this.value.length > this.props.schema.maxLength) {
                this.errorMessage = this.props.locale.error.maxLength.replace("{0}", String(this.props.schema.maxLength));
                return;
            }
            if (this.props.schema.pattern !== undefined
                && !this.value.match(this.props.schema.pattern)) {
                this.errorMessage = this.props.locale.error.pattern.replace("{0}", String(this.props.schema.pattern));
                return;
            }
        }

        this.errorMessage = "";
    }
    public toggleOptional = () => {
        if (this.value === undefined) {
            this.value = common.getDefaultValue(this.props.schema, this.props.initialValue) as string;
            this.validate();
        } else {
            this.value = undefined;
        }
        this.setState({ value: this.value });
        this.props.updateValue(this.value);
    }
    public render() {
        let control: JSX.Element | null = null;
        if (this.value !== undefined) {
            if (this.props.schema.enum === undefined || this.props.readonly || this.props.schema.readonly) {
                control = (
                    <input className={this.props.theme.formControl}
                        type={this.props.schema.format}
                        onChange={this.onChange}
                        defaultValue={this.value}
                        readOnly={this.props.readonly || this.props.schema.readonly} />
                );
            } else {
                const options = this.props.schema.enum.map((e, i) => <option key={i} value={e} >{e}</option>);
                control = (
                    <select className={this.props.theme.formControl}
                        type={this.props.schema.format}
                        onChange={this.onChange}
                        defaultValue={this.value}>
                        {options}
                    </select>
                );
            }
        }

        let errorDescription: JSX.Element | null = null;
        if (this.errorMessage) {
            errorDescription = <p className={this.props.theme.help}>{this.errorMessage}</p>;
        }
        let optionalCheckbox: JSX.Element | null = null;
        if (!this.props.required) {
            optionalCheckbox = (
                <div className={this.props.theme.optionalCheckbox}>
                    <label>
                        <input type="checkbox" onChange={this.toggleOptional} checked={this.value === undefined} />
                        is undefined
                    </label>
                </div>
            );
        }
        return (
            <div className={this.errorMessage ? this.props.theme.errorRow : this.props.theme.row}>
                <TitleEditor {...this.props} />
                {optionalCheckbox}
                {control}
                <p className={this.props.theme.help}>{this.props.schema.description}</p>
                {errorDescription}
            </div>
        );
    }
}

// src/angular/string-editor.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import * as common from "../common";

@Component({
    selector: "string-editor",
    template: `
    <div [class]="errorMessage ? theme.errorRow : theme.row">
        <title-editor [title]="title"
            (onDelete)="onDelete.emit()"
            [theme]="theme"
            [icon]="icon"
            [locale]="locale"
            [hasDeleteButton]="hasDeleteButton">
        </title-editor>
        <div *ngIf="!required" [class]="theme.optionalCheckbox">
            <label>
                <input type="checkbox" (change)="toggleOptional()" [checked]="value === undefined" />
                is undefined
            </label>
        </div>
        <textarea *ngIf="useTextArea()"
            [class]="theme.formControl"
            (change)="onChange($event)"
            rows="5"
            [readOnly]="readonly || schema.readonly">{{value}}</textarea>
        <input *ngIf="useInput()"
            [class]="theme.formControl"
            [type]="schema.format"
            (change)="onChange($event)"
            [defaultValue]="value"
            [readOnly]="readonly || schema.readonly" />
        <select *ngIf="useSelect()"
            [class]="theme.formControl"
            (change)="onChange($event)">
            <option *ngFor="let e of schema.enum; let i = index; trackBy:trackByFunction"
                [value]="e"
                [selected]="value === e">
                {{e}}
            </option>
        </select>
        <p [class]="theme.help">{{schema.description}}</p>
        <p *ngIf="errorMessage" [class]="theme.help">{{errorMessage}}</p>
    </div>
    `,
})
export class StringEditorComponent {
    @Input()
    schema: common.StringSchema;
    @Input()
    initialValue: string;
    @Input()
    title?: string;
    @Output()
    updateValue = new EventEmitter();
    @Input()
    theme: common.Theme;
    @Input()
    icon: common.Icon;
    @Input()
    locale: common.Locale;
    @Output()
    onDelete = new EventEmitter();
    @Input()
    readonly?: boolean;
    @Input()
    required?: boolean;
    @Input()
    hasDeleteButton: boolean;

    value?: string;
    errorMessage: string;
    ngOnInit() {
        this.value = common.getDefaultValue(this.required, this.schema, this.initialValue) as string;
        this.validate();
        this.updateValue.emit(this.value);
    }
    useTextArea() {
        return this.value !== undefined && (this.schema.enum === undefined || this.readonly || this.schema.readonly) && this.schema.format === "textarea";
    }
    useInput() {
        return this.value !== undefined && (this.schema.enum === undefined || this.readonly || this.schema.readonly) && this.schema.format !== "textarea";
    }
    useSelect() {
        return this.value !== undefined && (this.schema.enum !== undefined && !this.readonly && !this.schema.readonly);
    }
    onChange(e: { target: { value: string } }) {
        this.value = e.target.value;
        this.validate();
        this.updateValue.emit(this.value);
    }
    validate() {
        if (this.value !== undefined) {
            if (this.schema.minLength !== undefined
                && this.value.length < this.schema.minLength) {
                this.errorMessage = this.locale.error.minLength.replace("{0}", String(this.schema.minLength));
                return;
            }
            if (this.schema.maxLength !== undefined
                && this.value.length > this.schema.maxLength) {
                this.errorMessage = this.locale.error.maxLength.replace("{0}", String(this.schema.maxLength));
                return;
            }
            if (this.schema.pattern !== undefined
                && !new RegExp(this.schema.pattern).test(this.value)) {
                this.errorMessage = this.locale.error.pattern.replace("{0}", String(this.schema.pattern));
                return;
            }
        }

        this.errorMessage = "";
    }
    toggleOptional = () => {
        if (this.value === undefined) {
            this.value = common.getDefaultValue(true, this.schema, this.initialValue) as string;
            this.validate();
        } else {
            this.value = undefined;
        }
        this.updateValue.emit(this.value);
    }
    trackByFunction(index: number, value: { [name: string]: common.ValueType }) {
        return index;
    }
}
