// packages/angular/src/description.component.ts
import { Component, Input } from '@angular/core'
import * as common from 'schema-based-json-editor'

@Component({
  selector: 'description',
  template: `<p *ngIf="notEmpty || message" [class]="theme.help">{{message}}</p>`
})
export class DescriptionComponent {
  @Input()
    theme!: common.Theme
  @Input()
    message: string | undefined
  @Input()
    notEmpty?: boolean
}

// packages/react/src/description.tsx
import * as React from "react";
import * as common from "schema-based-json-editor";

/**
 * @public
 */
export class Description extends React.Component<{
    theme: common.Theme;
    message: string | undefined;
    notEmpty?: boolean;
}, {}> {
    render() {
        if (this.props.notEmpty || this.props.message) {
            return <p className={this.props.theme.help}>{this.props.message}</p>;
        }
        return null;
    }
}
