// src/angular/boolean-editor.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import * as common from "../common";

@Component({
    selector: "boolean-editor",
    template: `
    <div [class]="theme.row">
        <label [class]="theme.label">
            {{titleToShow}}
            <div [class]="theme.buttonGroup" [style]="buttonGroupStyle">
                <optional [required]="required"
                    [value]="value"
                    [isReadOnly]="isReadOnly"
                    [theme]="theme"
                    [locale]="locale"
                    (toggleOptional)="toggleOptional()">
                </optional>
                <icon *ngIf="hasDeleteButtonFunction"
                    (onClick)="onDelete.emit()"
                    [text]="icon.delete"
                    [theme]="theme"
                    [icon]="icon">
                </icon>
            </div>
        </label>
        <div *ngIf="value !== undefined">
            <div [class]="theme.radiobox">
                <label>
                    <input type="radio"
                        (change)="onChange($event)"
                        [checked]="value"
                        [disabled]="isReadOnly" />
                    {{locale.info.true}}
                </label>
            </div>
            <div [class]="theme.radiobox">
                <label>
                    <input type="radio"
                        (change)="onChange($event)"
                        [checked]="!value"
                        [disabled]="isReadOnly" />
                    {{locale.info.false}}
                </label>
            </div>
        </div>
        <description [theme]="theme" [message]="schema.description"></description>
    </div>
    `,
})
export class BooleanEditorComponent {
    @Input()
    schema: common.BooleanSchema;
    @Input()
    initialValue: boolean;
    @Input()
    title?: string;
    @Output()
    updateValue = new EventEmitter<common.ValidityValue<boolean | undefined>>();
    @Input()
    theme: common.Theme;
    @Input()
    icon: common.Icon;
    @Input()
    locale: common.Locale;
    @Output()
    onDelete = new EventEmitter();
    @Input()
    readonly?: boolean;
    @Input()
    required?: boolean;
    @Input()
    hasDeleteButton: boolean;

    value?: boolean;
    buttonGroupStyle = common.buttonGroupStyleString;
    ngOnInit() {
        this.value = common.getDefaultValue(this.required, this.schema, this.initialValue) as boolean;
        this.updateValue.emit({ value: this.value, isValid: true });
    }
    onChange(e: { target: { checked: boolean } }) {
        this.value = !this.value;
        this.updateValue.emit({ value: this.value, isValid: true });
    }
    toggleOptional() {
        this.value = common.toggleOptional(this.value, this.schema, this.initialValue) as boolean | undefined;
        this.updateValue.emit({ value: this.value, isValid: true });
    }
    get isReadOnly() {
        return this.readonly || this.schema.readonly;
    }
    get hasDeleteButtonFunction() {
        return this.hasDeleteButton && !this.isReadOnly;
    }
    get titleToShow() {
        return common.getTitle(this.title, this.schema.title);
    }
}

// src/react/boolean-editor.tsx
import * as React from "react";
import * as common from "../common";
import { Icon } from "./icon";
import { Optional } from "./optional";
import { Description } from "./description";

/**
 * @public
 */
export type Props = common.Props<common.BooleanSchema, boolean>;
/**
 * @public
 */
export type State = Partial<{
    value?: boolean;
    willRender: boolean;
}>;

/**
 * @public
 */
export class BooleanEditor extends React.Component<Props, State> {
    private value?: boolean;
    private willRender = false;
    constructor(props: Props) {
        super(props);
        this.value = common.getDefaultValue(this.props.required, this.props.schema, this.props.initialValue) as boolean;
    }
    componentDidMount() {
        this.props.updateValue(this.value, true);
    }
    shouldComponentUpdate(nextProps: Props, nextState: State) {
        if (this.willRender) {
            this.willRender = false;
            return true;
        }
        return this.props.initialValue !== nextProps.initialValue;
    }
    render() {
        const control = this.value !== undefined ? (
            <div>
                <div className={this.props.theme.radiobox}>
                    <label>
                        <input type="radio"
                            onChange={this.onChange}
                            checked={this.value}
                            disabled={this.isReadOnly} />
                        {this.props.locale.info.true}
                    </label>
                </div>
                <div className={this.props.theme.radiobox}>
                    <label>
                        <input type="radio"
                            onChange={this.onChange}
                            checked={!this.value}
                            disabled={this.isReadOnly} />
                        {this.props.locale.info.false}
                    </label>
                </div>
            </div>
        ) : null;

        return (
            <div className={this.props.theme.row}>
                <label className={this.props.theme.label}>
                    {this.titleToShow}
                    <div className={this.props.theme.buttonGroup} style={common.buttonGroupStyle}>
                        <Optional required={this.props.required}
                            value={this.value}
                            isReadOnly={this.isReadOnly}
                            theme={this.props.theme}
                            locale={this.props.locale}
                            toggleOptional={this.toggleOptional} />
                        <Icon valid={this.hasDeleteButtonFunction}
                            onClick={this.props.onDelete!}
                            text={this.props.icon.delete}
                            theme={this.props.theme}
                            icon={this.props.icon} />
                    </div>
                </label>
                {control}
                <Description theme={this.props.theme} message={this.props.schema.description} />
            </div>
        );
    }
    private onChange = (e: React.FormEvent<{ checked: boolean }>) => {
        this.value = !this.value;
        this.setState({ value: this.value });
        this.props.updateValue(this.value, true);
    }
    private toggleOptional = () => {
        this.value = common.toggleOptional(this.value, this.props.schema, this.props.initialValue) as boolean | undefined;
        this.willRender = true;
        this.setState({ value: this.value });
        this.props.updateValue(this.value, true);
    }
    private get isReadOnly() {
        return this.props.readonly || this.props.schema.readonly;
    }
    private get hasDeleteButtonFunction() {
        return this.props.onDelete && !this.isReadOnly;
    }
    private get titleToShow() {
        return common.getTitle(this.props.title, this.props.schema.title);
    }
}
