// src/angular/optional.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from "@angular/core";
import * as common from "../common";

@Component({
    selector: "optional",
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
    <div *ngIf="hasOptionalCheckbox" [class]="theme.optionalCheckbox">
        <label>
            <input type="checkbox" (change)="toggleOptional.emit()" [checked]="value === undefined" [disabled]="isReadOnly" />
            {{locale.info.notExists}}
        </label>
    </div>
    `,
})
export class OptionalComponent {
    @Input()
    required: boolean | undefined;
    @Input()
    value: common.ValueType | undefined;
    @Input()
    isReadOnly: boolean | undefined;
    @Input()
    theme: common.Theme;
    @Input()
    locale: common.Locale;
    @Output()
    toggleOptional = new EventEmitter();

    get hasOptionalCheckbox() {
        return !this.required && (this.value === undefined || !this.isReadOnly);
    }
}

// src/react/optional.tsx
import * as React from "react";
import * as common from "../common";

export class Optional extends React.Component<{
    required: boolean | undefined;
    value: common.ValueType | undefined;
    isReadOnly: boolean | undefined;
    theme: common.Theme;
    locale: common.Locale;
    toggleOptional: () => void;
}, {}> {
    render() {
        if (!this.props.required && (this.props.value === undefined || !this.props.isReadOnly)) {
            return (
                <div className={this.props.theme.optionalCheckbox}>
                    <label>
                        <input type="checkbox"
                            onChange={this.props.toggleOptional}
                            checked={this.props.value === undefined}
                            disabled={this.props.isReadOnly} />
                        {this.props.locale.info.notExists}
                    </label>
                </div>
            );
        }
        return null;
    }
}
